collections:
#- name: awx.awx
#- name: ansible.posix
- name: community.general
#- name: redhat_cop.controller_configuration
#- name: redhat_cop.ah_configuration
#- name: fortinet.fortimanager
#- name: amazon.aws
#- name: cisco.ios
#- name: ansible.netcommon
#- name: ansible.utils
#- name: servicenow.itsm
#- name: ansible.controller
#- name: redhat.rhel_system_roles
