collections:
- name: ansible.posix
  version: 1.3.0
- name: amazon.aws
  version: 3.0.0
- name: cisco.ios
  version: 2.6.0
- name: ansible.netcommon
  version: 2.5.0
- name: ansible.utils
  version: 2.4.3
- name: community.general
  version: 4.5.0
- name: awx.awx
  version: 20.0.1
