collections:
- name: ansible.posix
- name: community.general
  version: 4.4.0
#- name: amazon.aws
#- name: cisco.ios
#- name: ansible.netcommon
#- name: ansible.utils
#- name: servicenow.itsm
#- name: ansible.controller
