---
- hosts: all
  gather_facts: false

  tasks:
  - name: Update sudoers
    community.general.sudoers:
      name: awx_sudo_access
      state: present
      user: redhat
      runas: root
      commands: ALL
      nopassword: yes
